version: '3'

services:
  master:
    image: my/jmeter
    container_name: master
    hostname: master
    command: master
    tty: true
    ports:
      - "60000"
    networks:
      - jmeter-network       
  server:
    image: my/jmeter
    command: server
    tty: true
    ports:
      - "50000"
      - "1099"
    networks:
      - jmeter-network
    depends_on:
      - master

networks:
  jmeter-network:
    driver: bridge